openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /users/{id}:
    post:
      summary: Update a user's email
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The user ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input