openapi: 3.0.0
info:
  title: User Registration API
  version: "1.0.0"
servers:
  - url: https://api.yourwebsite.com/v1
paths:
  /users:
    post:
      summary: Registers a new user
      operationId: registerUser
      requestBody:
        description: User object that needs to be added to the system
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid user input received
components:
  schemas:
    User:
      type: object
      required:
        - username
        - password
        - email
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        username:
          type: string
          example: "johndoe"
        password:
          type: string
          format: password
          example: "mysecretpassword"
        email:
          type: string
          format: email
          example: "john@example.com"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
